Repository thoth-station/analyzer, pull requests merged in 2018-10, with the labels that each got.

#54 Automatic update of dependency pytest from 3.8.1 to 3.8.2
  Pipfile.lock
Labels: bot

#59 Report timestamp for an analyzer run
  thoth/analyzer/cli.py
Labels: size/XS

#62 Release of version 0.1.0
  CHANGELOG.md
  thoth/analyzer/__init__.py
Labels: bot, size/M

#66 Automatic update of dependency thoth-common from 0.3.6 to 0.3.14
  Pipfile.lock
Labels: bot

#67 Automatic update of dependency pytest from 3.8.2 to 3.9.3
  Pipfile.lock
Labels: bot

#68 using thoht-* jobs now
  .coafile
  .zuul.yaml
Labels: size/S

#69 Automatic update of dependency thoth-common from 0.3.14 to 0.3.15
  Pipfile.lock
Labels: bot

#70 Automatic update of dependency thoth-common from 0.3.15 to 0.3.16
  Pipfile.lock
Labels: bot
