Repository thoth-station/analyzer, pull requests merged in 2018-07, with the labels that each got.

#6 preparing release 0.0.7
  .coafile
  .travis.yml
  .zuul.yaml
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  thoth/analyzer/__init__.py
  thoth/analyzer/cli.py
  thoth/analyzer/command.py
Labels: approved, size/XL

#20 Automatic update of dependency thoth-common from 0.0.8 to 0.1.0
  Pipfile.lock
Labels: approved, bot

#19 Automatic update of dependency pytest from 3.6.2 to 3.6.3
  Pipfile.lock
Labels: bot

#22 Automatic update of dependency thoth-common from 0.1.0 to 0.2.0
  Pipfile.lock
Labels: bot

#24 Initial dependency lock
  Pipfile.lock
Labels: bot

#26 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#27 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#29 Update requirements.txt respecting requirements in Pipfile
  requirements.txt
Labels: bot, size/XS
