Repository thoth-station/analyzer, pull requests merged in 2019-09, with the labels that each got.

#179 Add dry-run
  thoth/analyzer/cli.py
Labels: approved, size/XS

#180 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#181 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#182 Fix handling of non-json values as parameters
  thoth/analyzer/cli.py
Labels: approved, size/XS

#184 Release of version 0.1.3
  CHANGELOG.md
  thoth/analyzer/__init__.py
Labels: bot, size/M

#185 Automatic update of dependency pytest from 5.1.2 to 5.1.3
  Pipfile.lock
Labels: bot

#186 Add duration for analyzer results
  thoth/analyzer/cli.py
Labels: approved, size/XS

#188 Release of version 0.1.4
  CHANGELOG.md
  thoth/analyzer/__init__.py
Labels: bot, size/XS

#189 Automatic update of dependency pytest from 5.1.3 to 5.2.0
  Pipfile.lock
Labels: bot
