Repository thoth-station/analyzer, pull requests merged in 2019-03, with the labels that each got.

#137 Automatic update of dependency pytest from 4.3.0 to 4.3.1
  Pipfile.lock
Labels: bot

#138 Use Sphinx for documentation
  .coafile
  .gitignore
  README.rst
  docs/source/conf.py
  docs/source/index.rst
  setup.py
Labels: size/L

#139 Automatic update of dependency thoth-common from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot

#140 Automatic update of dependency thoth-common from 0.8.0 to 0.8.1
  Pipfile.lock
Labels: bot

#141 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#142 Automatic update of dependency pytest from 4.3.1 to 4.4.0
  Pipfile.lock
Labels: bot
