Repository thoth-station/analyzer, pull requests merged in 2019-11, with the labels that each got.

#203 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#204 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#205 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/XS

#206 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/XS

#207 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#208 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#211 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L

#209 Report document id based on variable supplied
  thoth/analyzer/cli.py
Labels: approved, size/XS

#213 Release of version 0.1.5
  CHANGELOG.md
  thoth/analyzer/__init__.py
Labels: bot, size/S

#214 Automatic update of dependency thoth-common from 0.9.17 to 0.9.18
  Pipfile.lock
Labels: bot, size/XS

#215 Automatic update of dependency thoth-common from 0.9.18 to 0.9.19
  Pipfile.lock
Labels: bot, size/XS
