Repository thoth-station/analyzer, pull requests merged in 2019-12, with the labels that each got.

#217 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/M

#219 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/S

#220 Gather operating system information for each analyzer
  thoth/analyzer/cli.py
Labels: approved, size/M

#218 Change Sphinx theme
  docs/source/conf.py
Labels: approved, size/XS

#222 Release of version 0.1.6
  CHANGELOG.md
  thoth/analyzer/__init__.py
Labels: bot, size/S

#223 Add Google Analytics
  docs/source/_templates/layout.html
Labels: approved, size/S

#226 Reformat using black
  thoth/analyzer/__init__.py
  thoth/analyzer/cli.py
  thoth/analyzer/command.py
Labels: approved, size/L

#225 Add Thoth's deployment name to document metadata
  thoth/analyzer/cli.py
Labels: size/XS

#227 Point documentation to other libraries
  docs/source/index.rst
Labels: approved, size/XS

#229 Release of version 0.1.7
  CHANGELOG.md
  thoth/analyzer/__init__.py
Labels: bot, size/XS

#230 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/M

#231 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/XS
