Repository thoth-station/analyzer, pull requests merged in 2019-02, with the labels that each got.

#122 Update year in sources
  thoth/analyzer/cli.py
  thoth/analyzer/command.py
Labels: size/XS

#123 Automatic update of dependency distro from 1.3.0 to 1.4.0
  Pipfile.lock
Labels: bot

#126 Automatic update of dependency pytest from 4.1.1 to 4.2.1
  Pipfile.lock
Labels: bot

#128 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#129 Release of version 0.1.1
  CHANGELOG.md
  thoth/analyzer/__init__.py
Labels: bot, size/M

#130 Fix repeated keyword argument
  setup.py
Labels: size/XS

#132 Release of version 0.1.2
  CHANGELOG.md
  thoth/analyzer/__init__.py
Labels: bot, size/XS

#133 Automatic update of dependency pytest from 4.2.1 to 4.3.0
  Pipfile.lock
Labels: bot
