Repository thoth-station/analyzer, pull requests merged in 2019-08, with the labels that each got.

#169 Add advise and provenance-checker managers
  .thoth.yaml
Labels: approved, size/XS

#171 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L

#173 Automatic update of dependency thoth-common from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#174 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#175 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#176 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#177 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot
