Repository thoth-station/analyzer, pull requests merged in 2020-04, with the labels that each got.

#269 Automatic update of dependency distro from 1.4.0 to 1.5.0
  Pipfile.lock
Labels: bot, size/L

#270 Automatic update of dependency thoth-common from 0.10.11 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#271 Use RHEL 8
  .thoth.yaml
Labels: approved, size/XS

#272 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/M

#273 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#274 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/XS

#275 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/L

#276 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/XS

#277 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot

#278 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/XS

#279 No need to have self in to_dict() method
  thoth/analyzer/command.py
Labels: approved

#280 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
